spring:
  application.name: device-api
  datasource:
    url: jdbc:h2:mem:devices-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    banner-mode: off
